### Data preprocessing

In [281]:
#1. Lets read the file to a dataframe and print all the rows and columns
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/lmanikon/lmanikon.github.io/master/teaching/datasets/airlineSatisfaction.csv')
df.head()

,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,70172,Male,Loyal Customer,13,Personal Travel,Eco Plus,460,3,4,3,...,5,4,3,4,4,5,5,25,18.0,neutral or dissatisfied
1,5047,Male,disloyal Customer,25,Business travel,Business,235,3,2,3,...,1,1,5,3,1,4,1,1,6.0,neutral or dissatisfied
2,110028,Female,Loyal Customer,26,Business travel,Business,1142,2,2,2,...,5,4,3,4,4,4,5,0,0.0,satisfied
3,24026,Female,Loyal Customer,25,Business travel,Business,562,2,5,5,...,2,2,5,3,1,4,2,11,9.0,neutral or dissatisfied
4,119299,Male,Loyal Customer,61,Business travel,Business,214,3,3,3,...,3,3,4,4,3,3,3,0,0.0,satisfied

In [282]:
#FInding the unique  values of satisfaction column
print(df['satisfaction'].unique())

['neutral or dissatisfied' 'satisfied']

In [283]:
#2. Find the total number of data points in this dataset?
print(df.shape[0])

103904

In [284]:
#3. Total number of attributes in this dataset
print(df.shape[1])

24

In [285]:
#4. Check if there are any missing values in this dataset -- if yes, print true or else print false
print(df.isnull().any().any())

True

In [286]:
#5. If there are missing values, print the total number of missing values
print(df.isnull().sum().sum())

310

In [287]:
#6. Now drop all the rows with atleast one missing value
df = df.dropna(how="any")
print(df.shape)
print(df.isnull().any().sum())

(103594, 24)
0

In [288]:
#7. Lets print the summary statistics
print(df.describe())

                  id            Age  Flight Distance  Inflight wifi service  \
count  103594.000000  103594.000000    103594.000000          103594.000000
mean    64942.428625      39.380466      1189.325202               2.729753
std     37460.816597      15.113125       997.297235               1.327866
min         1.000000       7.000000        31.000000               0.000000
25%     32562.250000      27.000000       414.000000               2.000000
50%     64890.000000      40.000000       842.000000               3.000000
75%     97370.500000      51.000000      1743.000000               4.000000
max    129880.000000      85.000000      4983.000000               5.000000

       Departure/Arrival time convenient  Ease of Online booking  \
count                      103594.000000           103594.000000
mean                            3.060081                2.756984
std                             1.525233                1.398934
min                             0.000000                0.000000
25%                             2.000000                2.000000
50%                             3.000000                3.000000
75%                             4.000000                4.000000
max                             5.000000                5.000000

       Gate location  Food and drink  Online boarding   Seat comfort  \
count  103594.000000   103594.000000    103594.000000  103594.000000
mean        2.977026        3.202126         3.250497       3.439765
std         1.277723        1.329401         1.349433       1.318896
min         0.000000        0.000000         0.000000       0.000000
25%         2.000000        2.000000         2.000000       2.000000
50%         3.000000        3.000000         3.000000       4.000000
75%         4.000000        4.000000         4.000000       5.000000
max         5.000000        5.000000         5.000000       5.000000

       Inflight entertainment  On-board service  Leg room service  \
count           103594.000000     103594.000000     103594.000000
mean                 3.358341          3.382609          3.351401
std                  1.333030          1.288284          1.315409
min                  0.000000          0.000000          0.000000
25%                  2.000000          2.000000          2.000000
50%                  4.000000          4.000000          4.000000
75%                  4.000000          4.000000          4.000000
max                  5.000000          5.000000          5.000000

       Baggage handling  Checkin service  Inflight service    Cleanliness  \
count     103594.000000    103594.000000     103594.000000  103594.000000
mean           3.631687         3.304323          3.640761       3.286397
std            1.181051         1.265396          1.175603       1.312194
min            1.000000         0.000000          0.000000       0.000000
25%            3.000000         3.000000          3.000000       2.000000
50%            4.000000         3.000000          4.000000       3.000000
75%            5.000000         4.000000          5.000000       4.000000
max            5.000000         5.000000          5.000000       5.000000

       Departure Delay in Minutes  Arrival Delay in Minutes
count               103594.000000             103594.000000
mean                    14.747939                 15.178678
std                     38.116737                 38.698682
min                      0.000000                  0.000000
25%                      0.000000                  0.000000
50%                      0.000000                  0.000000
75%                     12.000000                 13.000000
max                   1592.000000               1584.000000

In [289]:
#8. Lets say drop the column 'id'
df = df.drop(columns=['id'])
print(df)

        Gender      Customer Type  Age   Type of Travel     Class  \
0         Male     Loyal Customer   13  Personal Travel  Eco Plus
1         Male  disloyal Customer   25  Business travel  Business
2       Female     Loyal Customer   26  Business travel  Business
3       Female     Loyal Customer   25  Business travel  Business
4         Male     Loyal Customer   61  Business travel  Business
...        ...                ...  ...              ...       ...
103899  Female  disloyal Customer   23  Business travel       Eco
103900    Male     Loyal Customer   49  Business travel  Business
103901    Male  disloyal Customer   30  Business travel  Business
103902  Female  disloyal Customer   22  Business travel       Eco
103903    Male     Loyal Customer   27  Business travel  Business

        Flight Distance  Inflight wifi service  \
0                   460                      3
1                   235                      3
2                  1142                      2
3                   562                      2
4                   214                      3
...                 ...                    ...
103899              192                      2
103900             2347                      4
103901             1995                      1
103902             1000                      1
103903             1723                      1

        Departure/Arrival time convenient  Ease of Online booking  \
0                                       4                       3
1                                       2                       3
2                                       2                       2
3                                       5                       5
4                                       3                       3
...                                   ...                     ...
103899                                  1                       2
103900                                  4                       4
103901                                  1                       1
103902                                  1                       1
103903                                  3                       3

        Gate location  ...  Inflight entertainment  On-board service  \
0                   1  ...                       5                 4
1                   3  ...                       1                 1
2                   2  ...                       5                 4
3                   5  ...                       2                 2
4                   3  ...                       3                 3
...               ...  ...                     ...               ...
103899              3  ...                       2                 3
103900              4  ...                       5                 5
103901              3  ...                       4                 3
103902              5  ...                       1                 4
103903              3  ...                       1                 1

        Leg room service  Baggage handling  Checkin service  Inflight service  \
0                      3                 4                4                 5
1                      5                 3                1                 4
2                      3                 4                4                 4
3                      5                 3                1                 4
4                      4                 4                3                 3
...                  ...               ...              ...               ...
103899                 1                 4                2                 3
103900                 5                 5                5                 5
103901                 2                 4                5                 5
103902                 5                 1                5                 4
103903                 1                 4                4                 3

        Cleanliness  Departure Delay in Minutes  Arrival Delay in Minutes  \
0                 5                          25                      18.0
1                 1                           1                       6.0
2                 5                           0                       0.0
3                 2                          11                       9.0
4                 3                           0                       0.0
...             ...                         ...                       ...
103899            2                           3                       0.0
103900            4                           0                       0.0
103901            4                           7                      14.0
103902            1                           0                       0.0
103903            1                           0                       0.0

                   satisfaction
0       neutral or dissatisfied
1       neutral or dissatisfied
2                     satisfied
3       neutral or dissatisfied
4                     satisfied
...                         ...
103899  neutral or dissatisfied
103900                satisfied
103901  neutral or dissatisfied
103902  neutral or dissatisfied
103903  neutral or dissatisfied

[103594 rows x 23 columns]

In [290]:
#9. Categorical attributes to numerical attributes

#Gender
#Male -- 1; Female -- 0



#Can you write a Lambda function?
df['Gender'] = df['Gender'].apply(lambda x: 1 if x == 'Male' else 0)
print(df)

        Gender      Customer Type  Age   Type of Travel     Class  \
0            1     Loyal Customer   13  Personal Travel  Eco Plus
1            1  disloyal Customer   25  Business travel  Business
2            0     Loyal Customer   26  Business travel  Business
3            0     Loyal Customer   25  Business travel  Business
4            1     Loyal Customer   61  Business travel  Business
...        ...                ...  ...              ...       ...
103899       0  disloyal Customer   23  Business travel       Eco
103900       1     Loyal Customer   49  Business travel  Business
103901       1  disloyal Customer   30  Business travel  Business
103902       0  disloyal Customer   22  Business travel       Eco
103903       1     Loyal Customer   27  Business travel  Business

        Flight Distance  Inflight wifi service  \
0                   460                      3
1                   235                      3
2                  1142                      2
3                   562                      2
4                   214                      3
...                 ...                    ...
103899              192                      2
103900             2347                      4
103901             1995                      1
103902             1000                      1
103903             1723                      1

        Departure/Arrival time convenient  Ease of Online booking  \
0                                       4                       3
1                                       2                       3
2                                       2                       2
3                                       5                       5
4                                       3                       3
...                                   ...                     ...
103899                                  1                       2
103900                                  4                       4
103901                                  1                       1
103902                                  1                       1
103903                                  3                       3

        Gate location  ...  Inflight entertainment  On-board service  \
0                   1  ...                       5                 4
1                   3  ...                       1                 1
2                   2  ...                       5                 4
3                   5  ...                       2                 2
4                   3  ...                       3                 3
...               ...  ...                     ...               ...
103899              3  ...                       2                 3
103900              4  ...                       5                 5
103901              3  ...                       4                 3
103902              5  ...                       1                 4
103903              3  ...                       1                 1

        Leg room service  Baggage handling  Checkin service  Inflight service  \
0                      3                 4                4                 5
1                      5                 3                1                 4
2                      3                 4                4                 4
3                      5                 3                1                 4
4                      4                 4                3                 3
...                  ...               ...              ...               ...
103899                 1                 4                2                 3
103900                 5                 5                5                 5
103901                 2                 4                5                 5
103902                 5                 1                5                 4
103903                 1                 4                4                 3

        Cleanliness  Departure Delay in Minutes  Arrival Delay in Minutes  \
0                 5                          25                      18.0
1                 1                           1                       6.0
2                 5                           0                       0.0
3                 2                          11                       9.0
4                 3                           0                       0.0
...             ...                         ...                       ...
103899            2                           3                       0.0
103900            4                           0                       0.0
103901            4                           7                      14.0
103902            1                           0                       0.0
103903            1                           0                       0.0

                   satisfaction
0       neutral or dissatisfied
1       neutral or dissatisfied
2                     satisfied
3       neutral or dissatisfied
4                     satisfied
...                         ...
103899  neutral or dissatisfied
103900                satisfied
103901  neutral or dissatisfied
103902  neutral or dissatisfied
103903  neutral or dissatisfied

[103594 rows x 23 columns]

In [291]:
#10. Take the 'satisfaction' column and perform this conversion -- "neutral or dissatisfied": -1; "satisfied":1

df['satisfaction'] = df['satisfaction'].apply(lambda x: -1 if x == 'neutral or dissatisfied' else 1)
print(df)

        Gender      Customer Type  Age   Type of Travel     Class  \
0            1     Loyal Customer   13  Personal Travel  Eco Plus
1            1  disloyal Customer   25  Business travel  Business
2            0     Loyal Customer   26  Business travel  Business
3            0     Loyal Customer   25  Business travel  Business
4            1     Loyal Customer   61  Business travel  Business
...        ...                ...  ...              ...       ...
103899       0  disloyal Customer   23  Business travel       Eco
103900       1     Loyal Customer   49  Business travel  Business
103901       1  disloyal Customer   30  Business travel  Business
103902       0  disloyal Customer   22  Business travel       Eco
103903       1     Loyal Customer   27  Business travel  Business

        Flight Distance  Inflight wifi service  \
0                   460                      3
1                   235                      3
2                  1142                      2
3                   562                      2
4                   214                      3
...                 ...                    ...
103899              192                      2
103900             2347                      4
103901             1995                      1
103902             1000                      1
103903             1723                      1

        Departure/Arrival time convenient  Ease of Online booking  \
0                                       4                       3
1                                       2                       3
2                                       2                       2
3                                       5                       5
4                                       3                       3
...                                   ...                     ...
103899                                  1                       2
103900                                  4                       4
103901                                  1                       1
103902                                  1                       1
103903                                  3                       3

        Gate location  ...  Inflight entertainment  On-board service  \
0                   1  ...                       5                 4
1                   3  ...                       1                 1
2                   2  ...                       5                 4
3                   5  ...                       2                 2
4                   3  ...                       3                 3
...               ...  ...                     ...               ...
103899              3  ...                       2                 3
103900              4  ...                       5                 5
103901              3  ...                       4                 3
103902              5  ...                       1                 4
103903              3  ...                       1                 1

        Leg room service  Baggage handling  Checkin service  Inflight service  \
0                      3                 4                4                 5
1                      5                 3                1                 4
2                      3                 4                4                 4
3                      5                 3                1                 4
4                      4                 4                3                 3
...                  ...               ...              ...               ...
103899                 1                 4                2                 3
103900                 5                 5                5                 5
103901                 2                 4                5                 5
103902                 5                 1                5                 4
103903                 1                 4                4                 3

        Cleanliness  Departure Delay in Minutes  Arrival Delay in Minutes  \
0                 5                          25                      18.0
1                 1                           1                       6.0
2                 5                           0                       0.0
3                 2                          11                       9.0
4                 3                           0                       0.0
...             ...                         ...                       ...
103899            2                           3                       0.0
103900            4                           0                       0.0
103901            4                           7                      14.0
103902            1                           0                       0.0
103903            1                           0                       0.0

        satisfaction
0                 -1
1                 -1
2                  1
3                 -1
4                  1
...              ...
103899            -1
103900             1
103901            -1
103902            -1
103903            -1

[103594 rows x 23 columns]

In [292]:
#11. Flight distance -- Binarization

#FD >=1000 -- 1
#Otherwise, -- 0
df['Flight Distance'] = df['Flight Distance'].apply(lambda x: 1 if x >= 1000 else 0)
print(df)

        Gender      Customer Type  Age   Type of Travel     Class  \
0            1     Loyal Customer   13  Personal Travel  Eco Plus
1            1  disloyal Customer   25  Business travel  Business
2            0     Loyal Customer   26  Business travel  Business
3            0     Loyal Customer   25  Business travel  Business
4            1     Loyal Customer   61  Business travel  Business
...        ...                ...  ...              ...       ...
103899       0  disloyal Customer   23  Business travel       Eco
103900       1     Loyal Customer   49  Business travel  Business
103901       1  disloyal Customer   30  Business travel  Business
103902       0  disloyal Customer   22  Business travel       Eco
103903       1     Loyal Customer   27  Business travel  Business

        Flight Distance  Inflight wifi service  \
0                     0                      3
1                     0                      3
2                     1                      2
3                     0                      2
4                     0                      3
...                 ...                    ...
103899                0                      2
103900                1                      4
103901                1                      1
103902                1                      1
103903                1                      1

        Departure/Arrival time convenient  Ease of Online booking  \
0                                       4                       3
1                                       2                       3
2                                       2                       2
3                                       5                       5
4                                       3                       3
...                                   ...                     ...
103899                                  1                       2
103900                                  4                       4
103901                                  1                       1
103902                                  1                       1
103903                                  3                       3

        Gate location  ...  Inflight entertainment  On-board service  \
0                   1  ...                       5                 4
1                   3  ...                       1                 1
2                   2  ...                       5                 4
3                   5  ...                       2                 2
4                   3  ...                       3                 3
...               ...  ...                     ...               ...
103899              3  ...                       2                 3
103900              4  ...                       5                 5
103901              3  ...                       4                 3
103902              5  ...                       1                 4
103903              3  ...                       1                 1

        Leg room service  Baggage handling  Checkin service  Inflight service  \
0                      3                 4                4                 5
1                      5                 3                1                 4
2                      3                 4                4                 4
3                      5                 3                1                 4
4                      4                 4                3                 3
...                  ...               ...              ...               ...
103899                 1                 4                2                 3
103900                 5                 5                5                 5
103901                 2                 4                5                 5
103902                 5                 1                5                 4
103903                 1                 4                4                 3

        Cleanliness  Departure Delay in Minutes  Arrival Delay in Minutes  \
0                 5                          25                      18.0
1                 1                           1                       6.0
2                 5                           0                       0.0
3                 2                          11                       9.0
4                 3                           0                       0.0
...             ...                         ...                       ...
103899            2                           3                       0.0
103900            4                           0                       0.0
103901            4                           7                      14.0
103902            1                           0                       0.0
103903            1                           0                       0.0

        satisfaction
0                 -1
1                 -1
2                  1
3                 -1
4                  1
...              ...
103899            -1
103900             1
103901            -1
103902            -1
103903            -1

[103594 rows x 23 columns]

In [293]:
#12. Age attribute -- Discretize
#[7,27) -- 1
#[27,51) -- 2
#[51,85) -- 3
df['Age'] = df['Age'].apply(
  lambda x: 1 if x >= 7 and x < 27 else 2 if x >= 27 and x < 51 else 3 if x >= 51 and x < 85 else x
)

print(df)

        Gender      Customer Type  Age   Type of Travel     Class  \
0            1     Loyal Customer    1  Personal Travel  Eco Plus
1            1  disloyal Customer    1  Business travel  Business
2            0     Loyal Customer    1  Business travel  Business
3            0     Loyal Customer    1  Business travel  Business
4            1     Loyal Customer    3  Business travel  Business
...        ...                ...  ...              ...       ...
103899       0  disloyal Customer    1  Business travel       Eco
103900       1     Loyal Customer    2  Business travel  Business
103901       1  disloyal Customer    2  Business travel  Business
103902       0  disloyal Customer    1  Business travel       Eco
103903       1     Loyal Customer    2  Business travel  Business

        Flight Distance  Inflight wifi service  \
0                     0                      3
1                     0                      3
2                     1                      2
3                     0                      2
4                     0                      3
...                 ...                    ...
103899                0                      2
103900                1                      4
103901                1                      1
103902                1                      1
103903                1                      1

        Departure/Arrival time convenient  Ease of Online booking  \
0                                       4                       3
1                                       2                       3
2                                       2                       2
3                                       5                       5
4                                       3                       3
...                                   ...                     ...
103899                                  1                       2
103900                                  4                       4
103901                                  1                       1
103902                                  1                       1
103903                                  3                       3

        Gate location  ...  Inflight entertainment  On-board service  \
0                   1  ...                       5                 4
1                   3  ...                       1                 1
2                   2  ...                       5                 4
3                   5  ...                       2                 2
4                   3  ...                       3                 3
...               ...  ...                     ...               ...
103899              3  ...                       2                 3
103900              4  ...                       5                 5
103901              3  ...                       4                 3
103902              5  ...                       1                 4
103903              3  ...                       1                 1

        Leg room service  Baggage handling  Checkin service  Inflight service  \
0                      3                 4                4                 5
1                      5                 3                1                 4
2                      3                 4                4                 4
3                      5                 3                1                 4
4                      4                 4                3                 3
...                  ...               ...              ...               ...
103899                 1                 4                2                 3
103900                 5                 5                5                 5
103901                 2                 4                5                 5
103902                 5                 1                5                 4
103903                 1                 4                4                 3

        Cleanliness  Departure Delay in Minutes  Arrival Delay in Minutes  \
0                 5                          25                      18.0
1                 1                           1                       6.0
2                 5                           0                       0.0
3                 2                          11                       9.0
4                 3                           0                       0.0
...             ...                         ...                       ...
103899            2                           3                       0.0
103900            4                           0                       0.0
103901            4                           7                      14.0
103902            1                           0                       0.0
103903            1                           0                       0.0

        satisfaction
0                 -1
1                 -1
2                  1
3                 -1
4                  1
...              ...
103899            -1
103900             1
103901            -1
103902            -1
103903            -1

[103594 rows x 23 columns]

In [294]:
#13. perform random sampling
#Sample 100 random datapoints from our dataframe df -- sample without replacement
print(df.sample(n=100, replace=False))

       Gender   Customer Type  Age   Type of Travel     Class  \
13736       1  Loyal Customer    1  Personal Travel       Eco
22646       1  Loyal Customer    1  Business travel  Business
47144       0  Loyal Customer    2  Business travel  Business
42225       0  Loyal Customer    3  Business travel  Business
14971       1  Loyal Customer    2  Business travel  Business
...       ...             ...  ...              ...       ...
39965       1  Loyal Customer    2  Business travel  Eco Plus
71306       1  Loyal Customer    2  Business travel  Business
52447       0  Loyal Customer    2  Personal Travel       Eco
96501       0  Loyal Customer    1  Personal Travel  Eco Plus
75646       0  Loyal Customer    2  Business travel       Eco

       Flight Distance  Inflight wifi service  \
13736                0                      2
22646                1                      2
47144                1                      2
42225                1                      1
14971                0                      3
...                ...                    ...
39965                0                      4
71306                1                      1
52447                1                      1
96501                0                      2
75646                1                      5

       Departure/Arrival time convenient  Ease of Online booking  \
13736                                  4                       2
22646                                  1                       5
47144                                  2                       2
42225                                  1                       1
14971                                  2                       5
...                                  ...                     ...
39965                                  2                       2
71306                                  1                       1
52447                                  5                       1
96501                                  4                       2
75646                                  3                       3

       Gate location  ...  Inflight entertainment  On-board service  \
13736              1  ...                       2                 3
22646              5  ...                       2                 4
47144              2  ...                       4                 4
42225              1  ...                       5                 5
14971              2  ...                       3                 1
...              ...  ...                     ...               ...
39965              2  ...                       4                 4
71306              1  ...                       4                 4
52447              2  ...                       2                 3
96501              3  ...                       2                 3
75646              3  ...                       5                 5

       Leg room service  Baggage handling  Checkin service  Inflight service  \
13736                 3                 5                4                 4
22646                 4                 3                1                 4
47144                 4                 4                5                 4
42225                 4                 4                4                 5
14971                 1                 2                2                 3
...                 ...               ...              ...               ...
39965                 5                 4                4                 4
71306                 4                 4                5                 4
52447                 5                 5                5                 5
96501                 3                 5                5                 4
75646                 4                 3                2                 4

       Cleanliness  Departure Delay in Minutes  Arrival Delay in Minutes  \
13736            2                           0                       0.0
22646            2                           1                       3.0
47144            5                           8                       0.0
42225            5                          13                      11.0
14971            3                           0                       0.0
...            ...                         ...                       ...
39965            4                          16                      19.0
71306            3                           0                       0.0
52447            2                           1                      10.0
96501            2                           0                       0.0
75646            5                           0                       0.0

       satisfaction
13736            -1
22646            -1
47144             1
42225             1
14971            -1
...             ...
39965            -1
71306             1
52447            -1
96501            -1
75646             1

[100 rows x 23 columns]

In [295]:
#14. Split the dataframe df into X and y -- X-- corresponds to feature set; y -- class label

#X - excluding 'satisfaction'
#y - 'satisfaction'
#y = f(X) -- y-class label variable; X -- feature set
X = df.drop(columns=['satisfaction'])
y = df['satisfaction']
print(X)  
print(y)

        Gender      Customer Type  Age   Type of Travel     Class  \
0            1     Loyal Customer    1  Personal Travel  Eco Plus
1            1  disloyal Customer    1  Business travel  Business
2            0     Loyal Customer    1  Business travel  Business
3            0     Loyal Customer    1  Business travel  Business
4            1     Loyal Customer    3  Business travel  Business
...        ...                ...  ...              ...       ...
103899       0  disloyal Customer    1  Business travel       Eco
103900       1     Loyal Customer    2  Business travel  Business
103901       1  disloyal Customer    2  Business travel  Business
103902       0  disloyal Customer    1  Business travel       Eco
103903       1     Loyal Customer    2  Business travel  Business

        Flight Distance  Inflight wifi service  \
0                     0                      3
1                     0                      3
2                     1                      2
3                     0                      2
4                     0                      3
...                 ...                    ...
103899                0                      2
103900                1                      4
103901                1                      1
103902                1                      1
103903                1                      1

        Departure/Arrival time convenient  Ease of Online booking  \
0                                       4                       3
1                                       2                       3
2                                       2                       2
3                                       5                       5
4                                       3                       3
...                                   ...                     ...
103899                                  1                       2
103900                                  4                       4
103901                                  1                       1
103902                                  1                       1
103903                                  3                       3

        Gate location  ...  Seat comfort  Inflight entertainment  \
0                   1  ...             5                       5
1                   3  ...             1                       1
2                   2  ...             5                       5
3                   5  ...             2                       2
4                   3  ...             5                       3
...               ...  ...           ...                     ...
103899              3  ...             2                       2
103900              4  ...             5                       5
103901              3  ...             5                       4
103902              5  ...             1                       1
103903              3  ...             1                       1

        On-board service  Leg room service  Baggage handling  Checkin service  \
0                      4                 3                 4                4
1                      1                 5                 3                1
2                      4                 3                 4                4
3                      2                 5                 3                1
4                      3                 4                 4                3
...                  ...               ...               ...              ...
103899                 3                 1                 4                2
103900                 5                 5                 5                5
103901                 3                 2                 4                5
103902                 4                 5                 1                5
103903                 1                 1                 4                4

        Inflight service  Cleanliness  Departure Delay in Minutes  \
0                      5            5                          25
1                      4            1                           1
2                      4            5                           0
3                      4            2                          11
4                      3            3                           0
...                  ...          ...                         ...
103899                 3            2                           3
103900                 5            4                           0
103901                 5            4                           7
103902                 4            1                           0
103903                 3            1                           0

        Arrival Delay in Minutes
0                           18.0
1                            6.0
2                            0.0
3                            9.0
4                            0.0
...                          ...
103899                       0.0
103900                       0.0
103901                      14.0
103902                       0.0
103903                       0.0

[103594 rows x 22 columns]
0        -1
1        -1
2         1
3        -1
4         1
         ..
103899   -1
103900    1
103901   -1
103902   -1
103903   -1
Name: satisfaction, Length: 103594, dtype: int64

In [296]:
#15. Aggregate -- based on the type of travel -- summing up all the values
print(df.groupby('Type of Travel').sum())

                 Gender                                      Customer Type  \
Type of Travel
Business travel   35032  disloyal CustomerLoyal CustomerLoyal CustomerL...
Personal Travel   15986  Loyal CustomerLoyal CustomerLoyal CustomerLoya...

                    Age                                              Class  \
Type of Travel
Business travel  146443  BusinessBusinessBusinessBusinessBusinessBusine...
Personal Travel   63979  Eco PlusEcoEcoEco PlusEcoEcoEcoEcoEcoEcoEcoEco...

                 Flight Distance  Inflight wifi service  \
Type of Travel
Business travel            35240                 201755
Personal Travel             8463                  81031

                 Departure/Arrival time convenient  Ease of Online booking  \
Type of Travel
Business travel                             199699                  205970
Personal Travel                             117307                   79637

                 Gate location  Food and drink  ...  Inflight entertainment  \
Type of Travel                                  ...
Business travel         214639          232861  ...                  249456
Personal Travel          93763           98860  ...                   98448

                 On-board service  Leg room service  Baggage handling  \
Type of Travel
Business travel            245224            248249            261313
Personal Travel            105194             98936            114908

                 Checkin service  Inflight service  Cleanliness  \
Type of Travel
Business travel           235110            261454       239815
Personal Travel           107198            115707       100636

                 Departure Delay in Minutes  Arrival Delay in Minutes  \
Type of Travel
Business travel                     1065005                 1095283.0
Personal Travel                      462793                  477137.0

                 satisfaction
Type of Travel
Business travel         11803
Personal Travel        -25603

[2 rows x 22 columns]